### ISSUE TITLE
Some examples?

### ISSUE THREAD

**Issue by pranavr2003** [rayluo/brip#1]
This is great! Could you also add a few examples to demonstrate importing a package and using it with Brython? Some simple examples like numpy and requests would be great!

**Comment by rayluo** [comment]
Thanks for your interest! I've been working on a sample recently, and it is expected to be finished within days. I'll update this issue when it becomes available.

However, a quick response to your question, packages like `numpy` might never been supported in Brython's ecosystem, because Brython only runs pure Python packages. `numpy` is partially implemented in C.

**Comment by rayluo** [comment]
Hi @pranavr2003 , you have watched (i.e. subscribed) the notifications from this repo, so you might have received the news of the [recent 0.2.1 release](https://github.com/rayluo/brip/releases/tag/0.2.1). Part of the effort is to rewrite the [README of brip](https://github.com/rayluo/brip#brip---the-brython-package-installer), which contains a link to a sample project [Easter](https://github.com/rayluo/easter). Don't forget to also read the "Limitations" section at the end of brip's README.
